"""add deleted_at for soft delete

Revision ID: 635f6c37bed1
Revises: fa8d69e5233f
Create Date: 2026-09-06 17:17:23.296478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635f6c37bed1'
down_revision: Union[str, Sequence[str], None] = 'fa8d69e5233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'deleted_at')
    # ### end Alembic commands ###
