"""add memo to expenses

Revision ID: fa8d69e5233f
Revises: 0919b2c75485
Create Date: 2026-08-30 23:09:58.499702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8d69e5233f'
down_revision: Union[str, Sequence[str], None] = '0919b2c75485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('memo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'memo')
    # ### end Alembic commands ###
